In [1]:
import torch

In [3]:
#first axis is 3 which are arrays
#second axis is 4 which are numbers
#Rank3
t = torch.tensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]], dtype=torch.float32)

In [4]:
t.size()

torch.Size([3, 4])

In [5]:
t.shape

torch.Size([3, 4])

In [6]:
len(t.shape)

2

In [7]:
#converted shape to tensor and took the product
torch.tensor(t.shape).prod()

tensor(12)

In [8]:
#number of elements
t.numel()

12

In [9]:
#components values are factors of 12
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [10]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [11]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [12]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [13]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [14]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [16]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [18]:
#squeezing a function
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [24]:
#squeeze
z=t.reshape(1,12).squeeze()
print(z)
print(z.shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [30]:
#unsqueezed
print(z.unsqueeze(dim=0))
print(z.unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [31]:
#flatten
#it should be both reshape and squeeze
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [32]:
#in below code you see the output, the bracket has been removed
#from the output which we got earlier 
#thus below code flattens
def flatten(t):
    t=t.reshape(1,-1)
    t=t.squeeze()
    return t
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [33]:
#concatenation
t1=torch.tensor([[1,2],[2,4]])
t2=torch.tensor([[5,6],[7,8]])
torch.cat((t1,t2),dim=0)


tensor([[1, 2],
        [2, 4],
        [5, 6],
        [7, 8]])

In [34]:
torch.cat((t1,t2),dim=1)

tensor([[1, 2, 5, 6],
        [2, 4, 7, 8]])

In [36]:
def flattenh(t):
    t = t.reshape(1, t.size()[0] * t.size()[1])
    t = t.squeeze()
    return t
flattenh(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])