In [0]:
import torch

In [0]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7)

In [0]:
# Features are 5 random normal variables with rows and columns
features = torch.randn(1,5)
# True weights for our data, random normal variables again (taking shape of another tensor and then creating it)
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [0]:
# Exercise 1 to calculate sum and put in activation function
output=activation(torch.sum(features*weights)+1)


In [14]:
#matrix multiplication

y=activation(torch.mm(features,weights.view(5, 1))+bias)
print(y)

tensor([[0.2443]])


In [0]:

#to return new tensor with the same data as weights with size (a, b) >weights.shape(a,b)
#to return the same tensor with a different shape >weights.resize_(a,b)
#to return new tensor with the same data as weights with size (a, b) >weights.view(a,b)


In [15]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

#Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.

h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [16]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.57113816, 0.91030763, 0.24195849],
       [0.5843681 , 0.65368255, 0.06991365],
       [0.75448944, 0.90180075, 0.95096476],
       [0.87362536, 0.31923205, 0.86346829]])

In [17]:
#to get tensor from numpy array
b=torch.from_numpy(a)
b

tensor([[0.5711, 0.9103, 0.2420],
        [0.5844, 0.6537, 0.0699],
        [0.7545, 0.9018, 0.9510],
        [0.8736, 0.3192, 0.8635]], dtype=torch.float64)

In [19]:
#going back to numpy array
b.numpy()

array([[0.57113816, 0.91030763, 0.24195849],
       [0.5843681 , 0.65368255, 0.06991365],
       [0.75448944, 0.90180075, 0.95096476],
       [0.87362536, 0.31923205, 0.86346829]])

In [20]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.1423, 1.8206, 0.4839],
        [1.1687, 1.3074, 0.1398],
        [1.5090, 1.8036, 1.9019],
        [1.7473, 0.6385, 1.7269]], dtype=torch.float64)

In [21]:
a

array([[1.14227632, 1.82061526, 0.48391699],
       [1.1687362 , 1.3073651 , 0.1398273 ],
       [1.50897888, 1.8036015 , 1.90192952],
       [1.74725072, 0.6384641 , 1.72693658]])