In [1]:
!pip3 install torch

In [0]:
import torch

In [0]:
w = torch.tensor(3.0, requires_grad= True)
b = torch.tensor(1.0, requires_grad= True)


In [0]:
def forward(x):
  y=w*x + b
  return y

In [6]:
x = torch.tensor(2)
forward(x)

tensor(7., grad_fn=<AddBackward0>)

In [8]:
x = torch.tensor([[4],[7]])
forward(x)

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)

In [0]:
# new lesson using Linear Regression
import torch
from torch.nn import Linear

In [11]:
torch.manual_seed(1)
#Linear model created below is for every input there is a corresponding output
model = Linear(in_features =1, out_features =1)
print(model.bias, model.weight)
#so output which we get is in the form y=0.5153x-0.4414

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [12]:
#so in the above equation when we put intput x as 2 the output which we get is shown
x = torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)
